### ISSUE TITLE
Will the code of baselines (TrafficSim and SimNet) be released?

### ISSUE THREAD

**Issue by TimHo0331** [SysCV/TrafficBots#1]
Dear authors,
    Thank you for providing the code, a very interesting work!
    I notice that the result of the proposed method is compared with TrafficSim and SimNet. Can you release the code of these?
Thank you!

**Comment by TimHo0331** [comment]
Another question is, what is the base frequency used in PE ? It seems not metioned in the paper.
And it seems that the finial dimension of embeding vector become 4 * d_emb for equ.3, instead of d_emb ?

**Comment by zhejz** [comment]
Hi, thanks for liking our work! All code will be released, including our reimplemented version of TrafficSim and SimNet. However, since the reimplemented version are meant for ablation studies, they will be based on TrafficBots modules and differ from the original ones. 
The code is planned to be released after the ICRA conference. The trained checkpoints will not be released due to the regulation from Waymo.
The frequency of PE is 1e3 for position. The `d_emb` is different in Eq 1, 2 and 3. The `d_emb` is selected such that encoded state `s` has the same `hidden_dim`. For example in Eq 3. each of `PE(x), PE(y), AE(θ), MLP(u)` will output `hidden_dim/4`. After concatenation the encoded state `s` will have the dimension of `hidden_dim`.

**Comment by panda2020-sky** [comment]
Thank you for your reply!
I have a question that, do you normalize the xy coordinates before the positional encoding?

**Comment by zhejz** [comment]
Sorry for the delay. The code, including the baselines TrafficSim and SimNet, is now available at https://github.com/zhejz/TrafficBots
